test:
  stage: test
  image: dunglas/frankenphp:php8.3
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /internal/' # Only for external GitLab URLs
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - when: never

  before_script:
    - apt update && apt install -y git curl libcurl4-openssl-dev pkg-config
    - php -r 'copy("https://getcomposer.org/installer", "composer-setup.php");'
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - install-php-extensions \
      gd \
      intl \
      zip \
      opcache \
      curl \
      pdo_mysql \
      bcmath \
      xdebug \
      xsl
    - echo xdebug.mode=coverage >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  script:
    - composer install
    - ./vendor/bin/testbench vendor:publish --tag="filament-package_ffhs_custom_forms-migrations"
    - ./vendor/bin/testbench workbench:build
    - php vendor/bin/pest --coverage
  coverage: /Total:\s*([^%]+)/

