default:
  interruptible: true

stages:
  - setup
  - build
  - test
  - stan
  - publish

include:
  - local: gitlab-ci/run_before_merge.gitlab-ci.yml
  - local: gitlab-ci/run_after_merge.gitlab-ci.yml
